### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by brogeby** [kristiandupont/kanel#402]
Hi!

I'm getting the follow error and stack trace after a bare minimum setup on v3.2.2, following your guide.

```
RangeError: Maximum call stack size exceeded
    at Array.find (<anonymous>)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:47:39)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:49:20)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:49:20)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:49:20)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:49:20)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:49:20)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:49:20)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:49:20)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:49:20)
```

After some investigating this seems to be an issue related to larger databases. I tried with a smaller database with fewer tables and columns and it worked fine. But when trying on my larger one, it fails with the above error.

**Comment by kristiandupont** [comment]
Got it. So it obviously shouldn't hang in that situation, but it's not completely clear to me what the preferred solution would be. Can you explain to me what your schema looks like (just the parts with the cyclic foreign keys) and what the rationale is for this design?

**Comment by brogeby** [comment]
So we have a few, basically the same.. For example we could have two rows in the table `files`, where one is referencing the other with the column `original_file_id`.

Another example would be 
`table_x.latest_table_y_id` referencing => `table_y.id`
`table_y.table_x_id` referencing => `table_x.id`

I don't really have a rationale behind this design, it was created before my time at this project but it seems to be a shortcut made to make it easier while writing code.

**Comment by Traivok** [comment]
I'm having a similar problem, i have a database with hundreds definitions and the call stack size is not enough, i tried to use --stack-size up to my available RAM and now i'm having a seg fault. 

### versions
- 		"kanel": "^3.3.1",
- 		"kanel-knex": "^2.1.0"

**Comment by kristiandupont** [comment]
@Traivok I imagine you are also getting an infinite loop, not an actual stack size problem (though I am not 100% sure). Do you have cyclic references in your schema?

**Comment by kristiandupont** [comment]
Ah, nice work! Do you mean to create a PR? I am very busy with other things at the moment..

**Comment by kristiandupont** [comment]
I just published a version with @pmoghaddam's fix which possibly solves this issue. Please let me know if it works!

**Comment by brogeby** [comment]
Unfortunately this didn't solve my issue. I guess you would have to keep track of which columns has already been resolved somehow?

**Comment by kristiandupont** [comment]
:-( Have you tried setting [resolveViews](https://kristiandupont.github.io/kanel/configuring.html#resolveviews) to `false`? It will mean that your views won't have branded ID types but perhaps you can live with that?

**Comment by brogeby** [comment]
Thanks for the suggestion!

I tried it but I still get Maximum call stack size exceeded but with two different stack traces. Without changing anything I get either of the following two.
```
RangeError: Maximum call stack size exceeded
    at String.split (<anonymous>)
    at mixed (/Users/brogeby/Projects/kerberos/node_modules/@kristiandupont/recase/index.js:19:8)
    at /Users/brogeby/Projects/kerberos/node_modules/@kristiandupont/recase/node_modules/ramda/src/internal/_pipe.js:3:27
    at /Users/brogeby/Projects/kerberos/node_modules/@kristiandupont/recase/node_modules/ramda/src/internal/_arity.js:11:19
    at /Users/brogeby/Projects/kerberos/node_modules/@kristiandupont/recase/index.js:37:68
    at /Users/brogeby/Projects/kerberos/node_modules/@kristiandupont/recase/node_modules/ramda/src/internal/_curryN.js:46:27
    at /Users/brogeby/Projects/kerberos/node_modules/@kristiandupont/recase/node_modules/ramda/src/internal/_arity.js:11:19
    at Object.defaultGetMetadata [as getMetadata] (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/default-metadata-generators.js:21:15)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:98:33)
    at /Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:50:24
```

```
RangeError: Maximum call stack size exceeded
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:28:21)
    at /Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:50:24
    at Array.map (<anonymous>)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:36:46)
    at /Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:50:24
    at Array.map (<anonymous>)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:36:46)
    at /Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:50:24
    at Array.map (<anonymous>)
    at resolveType (/Users/brogeby/Projects/kerberos/node_modules/kanel/build/generators/resolveType.js:36:46)
```

**Comment by kristiandupont** [comment]
I am going to close this issue as it's been a long time. Let me know if the issue still exists and is worth debugging.
